all: arvoreB.c
	gcc arvoreB.c -o busca -g

# busca: arvoreB.o funcs.o
# 	gcc arvoreB.o funcs.o -o busca -g -Wall

# arvoreB.o: arvoreB.c arvoreB.h
# 	gcc -c arvoreB.c -o arvoreB.o -g -Wall

# funcs.o: funcs.c arvoreB.h
# 	gcc -c funcs.c -o funcs.o -g -Wall

	
clean:
	-rm -f *.o

purge: clean
	-rm -f busca a.out